services:
  # 1. FastAPI Python Backend Service
  backend:
    image: ghcr.io/bhavesh7801/intervibe/backend:latest
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: interview_prep_backend
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    environment:
      - PYTHONUNBUFFERED=1
    command: uvicorn server:app --host 0.0.0.0 --port 8000
    networks:
      - app-network

  # 2. React + Vite Nginx Frontend Service
  frontend:
    image: ghcr.io/bhavesh7801/intervibe/frontend:latest
    build:
      context: ./frontend/app
      dockerfile: Dockerfile
    container_name: interview_prep_frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

# Shared Internal Container Network
networks:
  app-network:
    driver: bridge
